### ISSUE TITLE
コメントをJSONで保存すると不正な構文のJSONが保存される

### ISSUE THREAD

**Issue by ame0011** [guest-nico/nicoNewStreamRecorderKakkoKari#10]
「同時にコメントも取得し保存する」から「JSONで保存」を選ぶと保存されるJSON形式のコメントは不正な構文になっている

全体を配列`[]`で包むと正しい構文になります

**Comment by guest-nico** [comment]
返信が遅れてしまい申し訳ありません。ご報告をいただきありがとうございます。
ver0.88.19(https://github.com/guest-nico/nicoNewStreamRecorderKakkoKari/commit/893bc2690664b87bb4518809808f2511f868d361 )にて修正してみました。
