### ISSUE TITLE
フォローのみしているチャンネル限定放送を録画開始時「接続エラー。」

### ISSUE THREAD

**Issue by nnn-revo2012** [guest-nico/nicoNewStreamRecorderKakkoKari#11]
フォローのみしている（入会はしていない）チャンネル限定放送を録画開始時
`接続エラー。10秒後リトライします。`と表示されます（多分以後ずっとリトライすると思われます）。  
フォローも入会もしていないチャンネル限定放送の場合は `require_community_member` で即終了します。  

### 原因  
util/util.cs の public static int getPageType(string res) で以下が引っかからないようです。  (gateページが廃止された頃から？)
```
else if (util.getRegGroup(res, "(チャンネル会員限定番組です。<br>)") != null) return 4;
```

コミュ限定はこのロジックでいいですが、チャンネル限定の場合はフォローと入会は別なのでここで誤判定する場合があります。
```
else if (res.IndexOf("isFollowerOnly&quot;:true") > -1 && res.IndexOf("isFollowed&quot;:false") > -1 && res.IndexOf("[&quot;noTimeshiftProgram") == -1) return 4;
```
### 修正  
上記の **isFollowed** を **isJoined** に修正し、チャンネル会員限定番組です の行はコメントアウトすれば、コミュ限定およびチャンネル限定両方とも正しく判定されると思います。

**Comment by guest-nico** [comment]
ご報告いただきありがとうございます。
https://github.com/guest-nico/nicoNewStreamRecorderKakkoKari/commit/92521875649bb3d2a90fec4f107b9e3e3ecc5386 にてutil.cs内のpublic static int getPageType(string res)を修正させていただきました。
また、詳しい修正箇所についてのご指摘をいただき感謝いたします。

**Comment by nnn-revo2012** [comment]
修正ありがとうございます。以下を確認いたしました。  
ちなみに入会してるチャンネル放送が正常に録画できるというチェックは当方できてませんが多分大丈夫かなと思います。  
コミュ掲示板の 2214 はこの件を言ってたのかもしれないですね。  
 - [x] フォローしているが入会していないチャンネル放送は `require_community_member` で即終了  
- [x] フォローも入会していないチャンネル放送は `require_community_member` で即終了  
- [x] フォローしているユーザーコミュ放送は正常に録画される
- [x] フォローしていないユーザーコミュ放送は  `require_community_member` で即終了  
- [x] 公式放送はフォローの有無にかかわらず録画される

**Comment by guest-nico** [comment]
ご確認いただきありがとうございます。うまく動作できており良かったです。
\>>2214さんのご意見につきましてはチャンネル限定放送について考えが及んでおりませんでした。
こちらの修正により改善できていれば幸いです。
ご指摘をいただき感謝いたします。
