### ISSUE TITLE
Got 0 comments when downloading timeshift livestreams

### ISSUE THREAD

**Issue by fireattack** [guest-nico/nicoNewStreamRecorderKakkoKari#13]
When I try to use the tool to download comments, it shows 

```
アリーナ席に0件ぐらいのコメントが見つかりました(追い出しコメント含む)
コメントの後処理を開始します
コメントの保存を完了しました
録画を完了しました

```

It used to work fine:

![image](https://user-images.githubusercontent.com/4130991/129926874-22df15ad-cbea-4352-a70d-5cc7f3087a7e.png)

I can still download video, just not comments.

Sorry for using English. I can read Japanese, so feel free to reply in Japanese.

**Comment by guest-nico** [comment]
debug version
https://github.com/guest-nico/nicoNewStreamRecorderKakkoKari/releases/download/releases/ver0.88.47.debug2.0.1.3.10.55.zip

日本語となってしまい申し訳ありません。
ご不便をおかけしてしまい申し訳ありません。時差の問題の可能性について、少し修正をしてみました。
もしこちらでも改善されていない場合、こちらのバージョンを実行した際に画面上に表示されるログの内容を教えていただけますと幸いです。

Google Translation:
I'm sorry I used Google Translate.
I apologize for any inconvenience. I modified the program for possible time difference issues.
If this version hasn't fixed it, please tell me the log message you see on the screen when you run this version.

**Comment by fireattack** [comment]
Thanks, I will test it later today (especially after a program just ended, to see if my time zone still affects it.)

**Comment by fireattack** [comment]
Thanks, it works now!

```
w 1629364504  lv lv332895062
アリーナ席に8110件ぐらいのコメントが見つかりました(追い出しコメント含む)
t {"thread":{"resultcode":0,"thread":"M.cEYg2ExPeZwSSgnRF4tb6g","last_res":8110,"ticket":,"revision":1,"server_time":1629382506}}
2000件のコメントを保存しました
4000件のコメントを保存しました
```

**Comment by guest-nico** [comment]
ご報告いただきありがとうございます。うまく動作できており良かったです。また何かありましたらご連絡いただければ幸いです。

Google Translation:
Thank you for reporting. It was good that it worked well. If you have any problems, please feel free to contact.
