### ISSUE TITLE
optionForm.cs

### ISSUE THREAD

**Issue by nnn-revo2012** [guest-nico/nicoNewStreamRecorderKakkoKari#4]
前々から気になってたのですが、namaichi の中の optionForm.cs が app.config の下にtree登録されているので  src/gui に移動していません。

**Comment by guest-nico** [comment]
ご指摘をいただきありがとうございます。
https://github.com/guest-nico/nicoNewStreamRecorderKakkoKari/commit/3d6e9ce843d47f79facfc8c0646c99cf661e1853 にて修正してみました。
あまり整理されていないままになってしまっており申し訳ありません。

**Comment by nnn-revo2012** [comment]
移動してるのを確認いたしました。ありがとうございます。
