### ISSUE TITLE
0.87.86 録画開始時に「 (404) 見つかりません」ほか

### ISSUE THREAD

**Issue by nnn-revo2012** [guest-nico/nicoNewStreamRecorderKakkoKari#6]
ＴＳでログ取りながら録画テストしてます。
1.録画開始時に「リモート サーバーがエラーを返しました: (404) 見つかりません」ってログに出てます。
stream_sync.jsonを出すタイミングかな？と思ったのですが、URLをよく見ると、
https://pc126139fb4.dmc.nico************448ffd845397e/1/stream_sync.json?start_time=-575868010609&ht2_nicolive=2********wtj&start=590
になってます。開発ツールで見ると、
https://pc126139fb4.dmc.nico************448ffd845397e/stream_sync.json?ht2_nicolive=2********wtj
なので間違ってます。これが原因で404かわかりませんが。

2.コメントのテキスト出力時に コメント本文 をHtmlEncodeしてますでしょうか？
このバージョンより前からだと思いますが、放送によってはcommeonで読み込まないことがあるんですが多分不等号がそのまま入ってるとエラーになるんじゃないかと思います。

**Comment by guest-nico** [comment]
ご指摘をいただきありがとうございます。
1.stream_sync.jsonにつきましては、ご指摘の通り、URLが間違っており正常に取得できて
おりませんでした。https://github.com/guest-nico/nicoNewStreamRecorderKakkoKari/commit/1d8cfe69363df5798d688a607bc129fae0349466 にて修正させていただきました。
テストが足りておらず申し訳ありませんでした。

2.コメントのHtmlEncodeにつきましては、おそらくサーバーから受信した時点で
エンコードされているのではないかと認識していたため、特にエンコードはしておりませんでしたが
問題になる文字などがありますでしょうか？
もしくは、録画の終了処理がまだ完了していない間や、何らかの問題が起こっているとファイルの
末尾に「</packet>」が書き込まれておらず読み込めないことがあるかと思います。

**Comment by nnn-revo2012** [comment]
https://github.com/guest-nico/nicoNewStreamRecorderKakkoKari/commit/1d8cfe69363df5798d688a607bc129fae0349466 および releaseの v0.87.87 でTS録画時のstream_sync.jsonのURL、404エラーが出なくなったのを確認いたしました。ありがとうございます。
今更ですがリアルタイムだとstream_sync.jsonのURLが微妙に違うんですね。こっちはレスポンス帰って来てますがTSだと帰って来てないようで、TSの方はダミーなのかもしれませんね。
２についてはもうちょい検証してみてから改めて報告し直してみます。

**Comment by guest-nico** [comment]
ご確認いただきありがとうございます。
リアルタイム放送でのみテストしていたために、タイムシフト・追っかけ再生でURLがうまく生成できなく
なってしまっていたようでした。
2.につきまして、前回の投稿の最後の行がうまく表示できておりませんでしたが、括弧内は
「\</packet>」でした。コメントを取得する際にはJSONですが、書き込む際はXMLであるため、
もしかするとその差異から正常に出力できていない可能性もあるかもしれません。
ご指摘を頂きありがとうございました。
