### ISSUE TITLE
「録画開始」ボタンを押してログインに失敗したら自動的に録画を中止して欲しい

### ISSUE THREAD

**Issue by arigayas** [guest-nico/nicoNewStreamRecorderKakkoKari#7]
ニコ生新配信録画ツール（仮 ver0.88.01&0.1.3.10.26 を先ほどダウンロードして使いました。

1. 「ツール」→「オプション」でオプションウィンドウを開きます。
2. 「アカウント設定」タブをクリックします。
3. 「ニコニコ動画アカウント共有（略）」の「次のブラウザとクッキーを共有する」をクリックします。
4. (ニコニコ動画アカウント名が表示されている)Firefoxを指定して「OK」ボタンをクリックします。
5. メイン画面の「放送URL」に録画したいURLをコピペします。
6. 「録画開始」ボタンをクリックします。
### 実際の動作
7. ログ表示部分に
> 前回のユーザーセッションが見つかりませんでした。ブラウザからユーザーセッションを取得しました。ログインに失敗しました

と表示されたままになります。
![image](https://user-images.githubusercontent.com/11251874/83822286-8cfb9c00-a70b-11ea-8bda-9aa67efc762d.png)
### 期待する動作
7. 「録画開始」ボタンを押してログインに失敗したら自動的に録画を中止して「ログインに失敗しました。＜改行＞lv番号」のダイアログボックスが表示して欲しいです。
![image](https://user-images.githubusercontent.com/11251874/83822464-1317e280-a70c-11ea-852d-79bbe509d3f5.png)

### 使用環境
- Windows10 Pro 1909
- Firefox 68.9.0esr (64 ビット)
- ニコ生新配信録画ツール（仮 ver0.88.01&0.1.3.10.26

_ちなみに「ブラウザとクッキーを共有せず、次のアカウントでログインする」にチェックを入れてタイムシフトの録画は出来ました。_

**Comment by nnn-revo2012** [comment]
再現方法(0.88.1  6/5 5:50タイムスタンプのEXE)
ブラウザーでログイン→録画ツール（仮のオプションでブラウザーを選ぶ→ブラウザーでログアウト→録画ツールでlvxxxxxと入れて録画→エラー
これはFireFox  ESRだけでなくChromeでも再現しました（微妙にエラー違うけど）

コミュの掲示板1754によると0.88.1で暫定修正してるようなので原因は特定済みだと思うのですが、(ツールログイン＆ブラウザクッキー取得で)セッションとセキュアーセッションをCookieにセットした後放送ページをゲットする前にログインできているかマイページにでもアクセスして判定するのが良いかと思います。

      var hs = getPageSource(マイページのURL);
       result =Regex.IsMatch(hs, "user\\.login_status += +\\'login\\'", RegexOptions.Compiled) ? true : false;
result の結果で分岐なりメッセージなりなんなり

**Comment by arigayas** [comment]
他のブラウザ(Chrome)でも再現したのなら対応してほしいですね。

**Comment by guest-nico** [comment]
>>arigayas様
ご不便をおかけしてしまい申し訳ありません。
https://github.com/guest-nico/nicoNewStreamRecorderKakkoKari/commit/6c3b491d0743f025c8d74ced4bd002a7d0655cb0 でログインに失敗している際にメッセージボックスを表示して録画を終了するように修正してみました。
また、表示を拝見したところ、ログインができていながら視聴ページが正常に取得できていない可能性もあるため表示を修正いたしました。
そのような現象が起こる理由についてはまだ分かっておりません。
Firefoxで一度ログアウトした後にログインし直したり、別のブラウザを試してみても改善はされないでしょうか？

>>nnn-revo2012様
ご指摘をいただきありがとうございます。
ログインの失敗とページの取得の区別が分かりにくい表示になってしまっており、ご心配をおかけしてしまい申し訳ありません。
それぞれの場合の表示につきましてはver0.88.02にて少し修正してみました。
ログインの確認につきましては、以前にマイページへのアクセス過多で負荷の問題があった気がしますので、念のために別の何らかのページで確認をできるように修正してみたいと思います。
ログインやページの取得の問題に関してはまだ原因が掴めておりません。もう少し詳しい状況が分かると助かるかもしれません。

**Comment by arigayas** [comment]
@guest-nico さん
要望を受け入れていただきありがとうございます。
早速（仮 ver0.88.02&0.1.3.10.27をダウンロードし確認しました。
要望通りの動作になってました！ありがとうございます。

助言の通りにFirefox 68.9.0esr (64 ビット)で一度ログアウトした後にログインし直しましたが、
「ログインに失敗しました」になり駄目ですね。

試しにFirefox Developer Edition 78.0b1 (64 ビット)用のプロファイルを使ってニコニコにログインしました。
「アカウント設定」タブでFirefox Developer Editionのクッキーを指定して、
「録画開始」ボタンを押してみたら「タイムシフト録画設定」ウィンドウが表示されたので設定したら、
録画開始されてしばらく待ったら録画完了しました。
どういう事だ(苦笑)

@nnn-revo2012 さんから何かコメントが無ければこのissueを閉じようと思います。

**Comment by nnn-revo2012** [comment]
>ログインやページの取得の問題に関してはまだ原因が掴めておりません。  

FireFoxのクッキーの件やページ取得の件、何かわかるようならissue立てるかユーザー寄りの件でしたらコミュの掲示板に書かせていただきます。  

@arigayas 様
本issueは閉じていただいて構いません。

**Comment by arigayas** [comment]
ちょっと気になるので一言。Firefoxは頭文字だけが大文字です(´；ω；`)

Closeします。

**Comment by nnn-revo2012** [comment]
>Firefoxは頭文字だけが大文字です(´；ω；`)
ご指摘ありがとうございます。
